### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Jakousa** [vulle5/compareNHL#3]
# Katselmointi

### Mitä tein

* 4.9.2019 klo ~10:10

* Vertailin Wayne Gretzkyä ja Derian Hatcheria ja Joonas Kemppaista

### Kokemus

* Darkmode :heart_eyes:

* Kokemuksen yksinkertaisuudessa haetaan selkeästi minimalistisuutta, joka vaikuttaa toimivan todella hyvin.

* Yritin tehdä vertailuun pelaajan lisäystä oikean yläkulman hakupalkista. Tämä ei toiminut, mutta toiminta on hieman hämmentävä.

* Yritin jakaa vertailua kaverin kanssa mutta ainoastaan ensimmäinen pelaaja säilyi linkissä.

* En löytänyt tapaa päästä takaisin yhden pelaajan tietoihin kuten ensihaulla.

* Tällaisen flowin voisi korjata käytettävyydessä:
  * Hae pelaaja 1
  * Hae ja lisää pelaaja 2
  * Hae ja lisää pelaaja 3
  * Hae pelaajan 2 tarkemmat tiedot (esim painamalla nappia)
  * Palaa takaisin pelaajien 1, 2 ja 3 vertailuun (esim selaimen takaisin painikkeella)

* Tällä hetkellä edellä oleva vaatii tarpeettoman monta väliaskelta
  * Hae pelaaja 1
  * Paina add player
  * Hae ja lisää pelaaja 2
  * Paina add player
  * Hae ja lisää pelaaja
  * Hae pelaaja 2
  * Joko paina compare players tai paina selaimen takaisin painiketta
  * Hae puuttuvat pelaajat uudestaan

* Favicon ei oikein kuvasta sivua, bookmarkatessa sivun näkyy (reactin) atomi.

* Sivu kaikenkaikkiaan todella hyvän näköinen ja tuntuinen käyttää

## Koodi

* Koodi sijoitettu oikein nimettyihin tiedostoihin ja kansioihin. Hienoa!

* Suosittelen että luet https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html ja ehkä myös https://reactjs.org/docs/conditional-rendering.html.
  * Yleisesti suosittelen välttämään ehtolausekkeita returnin sisällä. Katso sekä komponentti että mapStateToProps https://github.com/vulle5/compareNHL/blob/0a65c0c841c82c6d1a5c78a9594ee47e7d9df897/client/src/components/compareView/CompareTile.js

* Voisit backendissä käyttää error handling middlewarea

* Kaikenkaikkiaan koodi on selkeää

## Kokonaisuus

* Minimalistinen projekti jonka hiomiseen on selkeästi käytetty aikaa

* Hyvää työtä, koodi on ylläpidettävää joten tästä olisi hyvä jatkaa kehittämistä!

🏒 / 🏅

**Comment by vulle5** [comment]
Kiitoksia näin rakentavasta ja syvälle viedystä kritiikistä. Nämä otetaan ehdottomasti, jatkokehitystä nähden huomioon. @Jakousa

**Comment by vulle5** [comment]
> Kiitoksia näin rakentavasta ja syvälle viedystä kritiikistä. Nämä otetaan ehdottomasti, jatkokehitystä nähden huomioon. @Jakousa

**Comment by vulle5** [comment]
Suuri osa ehdotuksista on nyt implementoitu. Suljetaan issue
